version: '3.2'
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
    image: murtarl/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
    image: murtarl/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  bootcamp_user_api:
    build:
      context: ../rafael-murta-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: murtarl/app-user-api:latest
    ports:
      - 8081:8081
    container_name: app-user-api
    environment:
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
  bootcamp_integration_api:
    build:
      context: ../rafael-murta-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: murtarl/app-integration-api:latest
    ports:
      - 8082:8082
    container_name: app-integration-api
    environment:
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
      - RABBIT_HOST=rabbitmq_bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
networks:
  backend:
    driver: "bridge"