spring:
  application:
    name: Bootcamp Sysmap 2024 - Rafael Lopes Murta
    main:
      allow-bean-definition-overriding: true
      allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /api
